export  const  FILES_LIMIT_ERROR = "Select at most 5 files";
export const  FILES_SIZE_LIMIT_ERROR = "The payload size is more than 5 MB";
export const  MAX_SIZE_LIMIT = 5000000;
export const  MAX_FILES_LIMIT = 5;
export const SITE_URL = "https://f135-2409-4051-4e0a-1e3d-e8af-e604-22be-d5.in.ngrok.io/"
export const SERVER_URL = "http://localhost:3001/"
export  const  SECURITY_KEY_NOT_PROVIDED_ERROR = "Security key not provided";
export  const  FILES_NOT_SELECTED_ERROR = "Select at least one file";
export const DUMMY_ERROR = "Something went wrong ... Please check your internet connection and try again";
